export const TOPNEWS_URL="https://gnews.io/api/v4/top-headlines?&max=15&apikey=36d3c5703163e8e264c57a90ec1220a9";

export const NEWS_URL="https://gnews.io/api/v4/search?&max=15&apikey=36d3c5703163e8e264c57a90ec1220a9";

export const countrylist = {
    Australia:'au',
    Brazil:'br',
    Canada:'ca',
    China:'ch',
    Egypt:'eg',
    France:'fr',
    Germany:'de',
    Greece:'gr',
    HongKong:'hk',
    India:'in',
    Ireland:'ie',
    Israel:'il',	
    Italy:'it',
    Japan:'jp',
    Netherlands:'nl',
    Norway:'no',
    Pakistan:'pk',
    Peru:'pe',
    Philippines:'ph',
    Portugal:'pt',
    Romania:'ro',
    RussianFederation:'ru',
    Singapore:'sg',
    Spain:'es',
    Sweden:'se',
    Switzerland:'ch',
    Taiwan:'tw',
    Ukraine	:'ua',
    UnitedKingdom:'gb',
    UnitedStates:'us',
}

export const languagelist = {
    Arabic:'ar',
    Chinese:'zh',
    Dutch:'nl',
    English:'en',
    French:'fr',
    German:'de',
    Greek:'el',
    Hebrew:'he',
    Hindi:'hi',
    Italian:'it',
    Japanese:'ja',
    Malayalam:'ml',
    Marathi:'mr',
    Norwegian:'no',
    Portuguese:'pt',
    Romanian:'ro',
    Russian:'ru',
    Spanish:'es',
    Swedish:'sv',
    Tamil:'ta',
    Telugu:'te',
    Ukrainian:'uk'
}
